<a href="https://colab.research.google.com/github/surajitaiml711-cloud/Swiggy-sales-analysis/blob/main/Swiggy_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **SWIGGY SALES ANALYSIS**

# **Import libraries**

In [171]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")
import plotly.express as px
import plotly.graph_objects as go

# **import data**

In [172]:
df = pd.read_excel("/content/drive/MyDrive/Colab Notebooks/EDA/Swiggy_sales/swiggy_data.xlsx")

In [173]:
df.head()

,State,City,Order Date,Restaurant Name,Location,Category,Dish Name,Price (INR),Rating,Rating Count
0,Karnataka,Bengaluru,2025-06-29,Anand Sweets & Savouries,Rajarajeshwari Nagar,Snack,Butter Murukku-200gm,133.9,4.0,0
1,Karnataka,Bengaluru,2025-04-03,Srinidhi Sagar Deluxe,Kengeri,Recommended,Badam Milk,52.0,4.5,25
2,Karnataka,Bengaluru,2025-01-15,Srinidhi Sagar Deluxe,Kengeri,Recommended,Chow Chow Bath,117.0,4.7,48
3,Karnataka,Bengaluru,2025-04-17,Srinidhi Sagar Deluxe,Kengeri,Recommended,Kesari Bath,65.0,4.6,65
4,Karnataka,Bengaluru,2025-03-13,Srinidhi Sagar Deluxe,Kengeri,Recommended,Mix Raitha,130.0,4.0,0

In [174]:
df.tail()

,State,City,Order Date,Restaurant Name,Location,Category,Dish Name,Price (INR),Rating,Rating Count
197425,Sikkim,Gangtok,2025-01-25,Mama's Kitchen,Gangtok,Momos,Soya cheese chilli momo ...,112.0,4.4,0
197426,Sikkim,Gangtok,2025-07-02,Mama's Kitchen,Gangtok,Momos,Kurkure momo fried ...,140.0,4.4,0
197427,Sikkim,Gangtok,2025-03-25,Mama's Kitchen,Gangtok,Momos,Chilli cheese momo,126.0,4.4,0
197428,Sikkim,Gangtok,2025-03-26,Mama's Kitchen,Gangtok,Momos,Veg Momos (8 Pc),85.0,4.4,0
197429,Sikkim,Gangtok,2025-03-27,Mama's Kitchen,Gangtok,Momos,Soya Momo,100.0,4.4,0

# **Meta Data**

In [175]:
print(f"No of rows : {df.shape[0]}")
print(f"No of columns : {df.shape[1]}")

No of rows : 197430
No of columns : 10

In [176]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 197430 entries, 0 to 197429
Data columns (total 10 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   State            197430 non-null  object
 1   City             197430 non-null  object
 2   Order Date       197430 non-null  datetime64[ns]
 3   Restaurant Name  197430 non-null  object
 4   Location         197430 non-null  object
 5   Category         197430 non-null  object
 6   Dish Name        197430 non-null  object
 7   Price (INR)      197430 non-null  float64
 8   Rating           197430 non-null  float64
 9   Rating Count     197430 non-null  int64
dtypes: datetime64[ns](1), float64(2), int64(1), object(6)
memory usage: 15.1+ MB

# **Data Types**

In [177]:
df.dtypes

State                      object
City                       object
Order Date         datetime64[ns]
Restaurant Name            object
Location                   object
Category                   object
Dish Name                  object
Price (INR)               float64
Rating                    float64
Rating Count                int64
dtype: object

In [178]:
df.describe()

,Order Date,Price (INR),Rating,Rating Count
count,197430,197430.000000,197430.000000,197430.000000
mean,2025-05-01 19:41:20.996808960,268.512920,4.341582,28.321805
min,2025-01-01 00:00:00,0.950000,1.500000,0.000000
25%,2025-03-01 00:00:00,139.000000,4.300000,0.000000
50%,2025-05-02 00:00:00,229.000000,4.400000,2.000000
75%,2025-07-01 00:00:00,329.000000,4.500000,15.000000
max,2025-08-31 00:00:00,8000.000000,5.000000,999.000000
std,NaN,219.338363,0.422585,87.542593

In [179]:
df.isnull().sum()

State              0
City               0
Order Date         0
Restaurant Name    0
Location           0
Category           0
Dish Name          0
Price (INR)        0
Rating             0
Rating Count       0
dtype: int64

# **KPI'S**

## **Total Sales (₹)**

In [180]:
total_sales = df['Price (INR)'].sum()
print("Total Sales (INR) :" ,round(total_sales,2))

Total Sales (INR) : 53012505.77

## **Average Rating**

In [181]:
average_rating = df['Rating'].mean()
print("Average Rating :" ,round(average_rating,1))

Average Rating : 4.3

## **Average Order Value (₹)**

In [182]:
avg_order_values = df['Price (INR)'].mean()
print("Average Order Value (INR) :" ,round(avg_order_values,2))

Average Order Value (INR) : 268.51

##  **Rating Count**

In [183]:
rating_count = df['Rating Count'].sum()
print("Rating Count :" ,rating_count)

Rating Count : 5591574

## **Total Orders**

In [184]:
total_orders = df['Order Date'].count()
print("Total Orders :" ,total_orders)

Total Orders : 197430

# **CHART DESIGN**

# **Monthly Sales Trend**

In [185]:
df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Month'] = df['Order Date'].dt.to_period('M').astype(str)
monthly_sales = df.groupby('Month')['Price (INR)'].sum().reset_index()

# fig = plt.figure(figsize=(10, 6))
# plt.plot(monthly_sales['Month'], monthly_sales['Price (INR)'], marker='o', linestyle='-')
# plt.xlabel('Month')
# plt.xticks(rotation=45)
# plt.ylabel('Total Sales (INR)')
# plt.title('Monthly Sales Trend')

fig = px.line(monthly_sales, x='Month', y='Price (INR)', title='Monthly Sales Trend')
fig.update_xaxes(tickangle=45)
fig.show()

# **Daily Sales Trend**

In [186]:
df["DayName"] = df["Order Date"].dt.day_name()
daily_sales = df.groupby("DayName")["Price (INR)"].sum().reindex(["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"])

# fig = plt.figure(figsize=(10, 6))
# plt.plot(daily_sales.index, daily_sales.values)
# plt.xlabel('Day of the Week')
# plt.xticks(rotation=45)
# plt.ylabel('Total Sales (INR)')
# plt.title('Daily Sales Trend')
# plt.show()

fig = px.bar(daily_sales, x=daily_sales.index, y=daily_sales.values, title="Daily Sales Trend")
fig.update_xaxes(tickangle=45)
fig.show()

# **Total Sales by Food Type (Veg vs Non-Veg)**

In [187]:
non_veg = [
    "chicken","egg","fish","kabab","kebab","mutton","biryani","Non-veg","Non veg","prawn","biriyani"
]

df["Food Category"] = np.where(df["Dish Name"].str.lower().str.contains('|'.join(non_veg),na=False), "Non-Veg", "Veg")

In [188]:
food_revenue = df.groupby("Food Category")["Price (INR)"].sum().reset_index()

In [189]:
import plotly.express as px

fig = px.pie(
    food_revenue,
    values="Price (INR)",
    names="Food Category",
    title="🍽️ Total Sales by Food Type",
    hole=0.45,   # Donut chart
    color="Food Category",
    color_discrete_map={
        "Veg": "#2ca02c",
        "Non-Veg": "#d62728"
    }
)

fig.update_traces(
    textposition="inside",
    textinfo="percent+label+value",
    pull=[0, 0.08],          # Pull out second slice
    marker=dict(line=dict(color="white", width=2)),
    hovertemplate="<b>%{label}</b><br>Sales: ₹%{value:,.0f}<br>Share: %{percent}<extra></extra>"
)

fig.update_layout(
    title={
        "text": "🍽️ Total Sales by Food Type",
        "x": 0.5,
        "xanchor": "center"
    },
    font=dict(size=16),
    legend_title="Food Category",
    template="plotly_white",
    width=700,
    height=500
)

fig.show()

# **Total Sales by State (Map Visualization)**

In [190]:
Total_sales_by_state = df.groupby("State",as_index=False)["Price (INR)"].sum().sort_values(by="Price (INR)",ascending=False)

In [191]:
import plotly.express as px

fig = px.bar(
    Total_sales_by_state,
    x="Price (INR)",
    y="State",
    color="State",
    orientation="h",
    title="📍 Total Sales by State",
    labels={
        "State": "State",
        "Price (INR)": "Total Sales (INR)"
    }
)

fig.update_layout(
    title_x=0.5,
    template="plotly_white",
    showlegend=False,
    height=600
)

fig.update_traces(
    texttemplate="₹%{x:,.0f}",
    textposition="outside"
)

fig.show()

# **Quarterly Performance Summary**

In [199]:
df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Quarter'] = df['Order Date'].dt.to_period('Q').astype(str)
quater_summary = df.groupby('Quarter',as_index=False).agg(
    Total_sales = ("Price (INR)","sum"),
    Average_rating = ("Rating","mean"),
    Total_orders = ("Order Date","count")
).sort_values(by="Quarter")

quater_summary["Total_sales"] = quater_summary["Total_sales"].apply(lambda x : round(x,0))
quater_summary["Average_rating"] = quater_summary["Average_rating"].apply(lambda x : round(x,2))


quater_summary

  Quarter  Total_sales  Average_rating  Total_orders
0  2025Q1   19667822.0            4.34         73096
1  2025Q2   19902257.0            4.34         74163
2  2025Q3   13442427.0            4.34         50171

# **Top 5 Cities by Sales**

In [200]:
top_5 = df.groupby("City",as_index=False)["Price (INR)"].sum().sort_values(by="Price (INR)",ascending=False).head(5)

In [203]:
fig = px.bar(
    top_5,
    x="Price (INR)",
    y="City",
    color="City",)
fig.show()

# **Weekly Trend Analysis**

In [211]:
weekly_trend = (
    df.groupby(df["Order Date"].dt.isocalendar().week)["Price (INR)"]
      .sum()

)

In [213]:
fig = px.line(
    weekly_trend,
    x=weekly_trend.index,
    y=weekly_trend.values,
    title="Weekly Trend Analysis",
    labels={"x": "Week", "y": "Total Sales (INR)"}
)

fig.update_layout(
    xaxis_title="Week",
    yaxis_title="Total Sales (INR)",
    template="plotly_white"
)

fig.show()